import type { Metadata } from "next";
import '../styles/globals.css'
import '../styles/style.css'
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Bizfinx79",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        <header>
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
