import type { Metadata } from "next";
import '../styles/globals.css'
import '../styles/style.css'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BackToTop from "@/components/BackToTop";

export const metadata: Metadata = {
  title: "Bizfinx79",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css"
        />
      </head>
      <body className="overflow-x-hidden">
        <BackToTop />
        <header>
          <Navbar />
        </header>
        <div className="">
          {children}
        </div>
        <div className="bg-foreground">
          <Footer />
        </div>
      </body>
    </html>
  );
}
